# Generated by Django 4.2.4 on 2023-12-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Purchase_Order_Model", "0002_alter_purchaseorder_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(null=True),
        ),
    ]
